# version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #healthcheck:
      #test: >
        #CMD-SHELL mongosh --username root --password example --authenticationDatabase admin --eval "db.adminCommand('ping')" --quiet
      #interval: 5s
      #timeout: 5s
      #retries: 5
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network
      


  mongo-express:
    image: mongo-express:latest
    restart: always

    depends_on:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH: 'false'  
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/?authSource=admin
    ports:
      - "8081:8081"
    networks:
      - my-network


  redis-commander:
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    restart: always
    depends_on:
      -  redis
        #condition: service_healthy
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8082:8081"
    networks:
      - my-network


  redis:
      image: redis:7.0
      restart: always
      ports:
        - "6379:6379"
      networks:
        - my-network
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  waze-scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    depends_on:
        - mongodb
        - redis
    environment:
        MONGO_URI: "mongodb://root:example@mongodb:27017/?authSource=admin"
        REDIS_HOST: redis
    networks:
        - my-network
    ports:
        - "5001:5000"

  traffic-generator:
    build:
      context: ./traffic-generator
      dockerfile: Dockerfile
    container_name: traffic_generator
    depends_on:
      waze-scraper:
        condition: service_started
    environment:
      GENERATOR_API_URL: http://waze-scraper:5000/ingest
      EVENTS_PER_SEC: 10
      DISTRIBUTION: deterministic
    networks:
      - my-network

  pig:
    build:
      context: ./pig
      dockerfile: Dockerfile
    image: my_pig:latest
    container_name: pig_ds
    depends_on:
      - mongodb     
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/?authSource=admin"
      MONGO_DBNAME: "waze_alertas"
      MONGO_COLLNAME: "eventos"
      PROXIMITY_THRESHOLD_METERS: 500
      TIME_WINDOW_MINUTES: 15
      OUTPUT_FORMAT: "csv"
      ENABLE_TEMPORAL_ANALYSIS: "true"
      ENABLE_GEOGRAPHIC_GROUPING: "true"      
    volumes:
      - mongo_export:/data/raw      
      - pig_output:/data/processed
      - ./pig/scripts:/scripts
    networks:
      - my-network
    stdin_open: true
    tty: true
    command: tail -f /dev/null  # Mantiene el contenedor corriendo
      

volumes:
  mongo_data:
  redis_data:
  mongo_export:
  pig_data_raw:
  pig_data_processed:
  pig_output:
  pig_logs:
  pig_scripts:  # Nuevo volumen para scripts y exports CSV

networks:
  my-network:
    driver: bridge